### ISSUE TITLE
Use consistent case for Latin characters in headers/titles

### ISSUE THREAD

**Issue by smikitky** [reactjs/ja.react.dev#163]
Currently, when article titles (rendered as `<h1>`) or headings (`<h2>` and so forth) include Latin characters, their cases are preserved or not preserved depending on the translators' preference (e.g., `Ref と DOM` vs `リストと key`). We have to come up with the common rule and fix the inconsistency.

----

もちろん "React" や "JavaScript" のような固有名詞は問答無用で先頭大文字でよいのですが、固有名詞とも言えないけどカタカナにするのも忍びない、"error boundary", "props", "state", "key", "ref" あたりが見出しにやってきた場合の扱いが現状では統一されていません。自分も記事によってやり方を変えてしまったりしているのですが、どこかでバシっとルールを決めて全体の統一性を上げる必要があると思います。

個人的には、右のナビゲーションに見出しが並んでいるのを見たときに小文字の語にちょっと違和感を感じたので、今は "Props" のように大文字にした方がいいのかなーという気がしていますが、来週になったら変わっているかもしれない程度の弱い感覚みたいなものです…。

**Comment by durgasatti** [comment]
please translate into English then I can make a review on your error
thank you

**Comment by smikitky** [comment]
新しい docs では、見出しや文頭であってもこれらの単語はキャピタライズしないという方向で統一したいと思います。「あくまでこれは日本語の文章なのだ」ということで。
