### ISSUE TITLE
一部の「副作用」を「エフェクト」に変更？

### ISSUE THREAD

**Issue by smikitky** [reactjs/ja.react.dev#585]
"(side) effect" をどう翻訳するかはいつも悩むのですが、旧ドキュメントでは原文が "side effect" であろうと "effect" であろうととにかく一貫して「副作用」と訳す方針にしていました。理由は以下の通りです。

- 原文ドキュメントで "side effect" と "effect" を一貫性のある基準で区別して使っているように思えない。むしろ同一視するような記載もある。例えば[旧サイトの useEffect の説明](https://legacy.reactjs.org/docs/hooks-effect.html)には
  > Data fetching, setting up a subscription, and manually changing the DOM in React components are all examples of **side effects**. Whether or not you’re used to calling these operations **“side effects” (or just “effects”)**, ...

  とあり、effect と side effect は事実上同じものであり単に effect の方が短くて便利から使うよ、という扱いに見える。

- 英語話者がどう感じるかはともかく、日本語訳がランダムに「作用」だったり「副作用」だったりすると明らかに混乱を招くので、何らかの統一は要る。

- 初学者がどう感じるかはともかく、プログラミング（特に関数型プログラミング）の文脈において[副作用の定義とは昔からこれ](https://ja.wikipedia.org/wiki/%E5%89%AF%E4%BD%9C%E7%94%A8_(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0))なので、useEffect がやっていることは（side がなくとも）「作用」より「副作用」と呼ぶことが妥当である。

---

ところが新サイトでは [Synchronizing with Effects](https://react.dev/learn/synchronizing-with-effects) で以下の方針が明記されており、わりと徹底されているように見えます。

> Here and later in this text, capitalized “Effect” refers to the React-specific definition above, i.e. a side effect caused by rendering. To refer to the broader programming concept, we’ll say “side effect”.

なんなら以下のような文章も出てきます。今の基準だと「副作用によって副作用を指定できます」と翻訳することになってしまいます。

> _Effects_ let you specify side effects that are caused by rendering itself, rather than by a particular event.

すべて見ていませんが、少なくとも [useEffect リファランス](https://react.dev/reference/react/useEffect)では、上記方針は守られています。

原文が `side effect` と `Effect` をこれだけ意図的に区別して書くようになった以上、日本語もそれに合わせた区別を導入することは妥当かつ有用なように思えす。

`Effect`（大文字）の具体的な訳語ですが、とりあえず「エフェクト」が妥当な気がしています。流石に「作用」はやっぱり混乱を招くと思いますし、「関数型言語の研究者ですらこれのことを "副作用" ではなく "エフェクト" と呼んでいる」というような話を[見た](https://twitter.com/search?q=%E9%96%A2%E6%95%B0%E5%9E%8B%20%E3%82%A8%E3%83%95%E3%82%A7%E3%82%AF%E3%83%88)こともあります。

ただ専門外すぎてこの方針で良いのかよく分かっていません。他の詳しい方の意見を聞きたいです。

**Comment by koba04** [comment]
> capitalized “Effect” refers to the React-specific definition above,

とあることから区別して Effect をエフェクトとするのは違和感ありません。
確かに使い分けないと Effect 関連のドキュメントで困る場面出てきそうですね。

**Comment by smikitky** [comment]
ありがとうございます。とりあえず「Effect = エフェクト, side effect = 副作用」の方針で進めてみて問題ありそうならまた相談させてください。

関連する主要記事の翻訳と useEffect リファレンスの修正が終わるまでは open しておきます。
