### ISSUE TITLE
(NITS) Windows 11 で閲覧すると本文が Yu Gothic UI になるのが気になる

### ISSUE THREAD

**Issue by honey32** [reactjs/ja.react.dev#639]
非常に細かいところで恐縮なのですが、

Mac で閲覧するときには無難なフォント (少なくとも私の環境では Hiragino Kaku Gothic ProN) が選ばれますが、Windows (少なくとも windows 11 では)の場合には本文が Yu Gothic UI になっているのが気になります。 

tailwind のデフォルトのフォント設定において、 `system-ui` の優先度が `sans-serif` よりも高いためだと考えます。

https://github.com/reactjs/ja.react.dev/blob/3d48615fb3f76b8b40cfaf55d8853feda8047925/tailwind.config.js#L69-L78

----

既存のフォントセットにカスタマイズを加えるのには知識不足から少し気が引けるのですが、ダメ元で良いなら上記ファイルを編集し、`defaultTheme.fontFamily.sans` 配列から `"system-ui"` を filter で除去する形で修正してしまっても大丈夫でしょうか？

（もしかしてこのプロジェクトでは編集できない要素だったりしたら…と思って質問させていただきます）

**Comment by smikitky** [comment]
編集自体は可能です。もうこれに慣れすぎていて個人的には特に不満は感じていませんが…

フォントを変える場合、英語の未翻訳記事の見た目が元サイトと変わらないことはどうしても条件になると思います。あと和文のイタリックが正しく表示できる必要もありそうです。

とりあえずPRを作っていただけるとプレビューが動くので、それを見て考えるのがいいかなと思います。

**Comment by honey32** [comment]
ありがとうございます！  やってみます！

**Comment by smikitky** [comment]
ところで[こんなの](https://twitter.com/honey321998/status/1682588941025935360)見つけましたが、修正提案は大歓迎ですのでよろしくお願いします。

**Comment by honey32** [comment]
見つかった...w ありがとうございます
