### ISSUE TITLE
APIリファレンスの各ページにある、見出し"Usage"に対する訳語を統一したい

### ISSUE THREAD

**Issue by roottool** [reactjs/ja.react.dev#699]
## 概要

- APIリファレンスの各ページにある、見出し"Usage"に対する訳語を統一させる。
- これは任意項目ですが、[Wikiの訳語の統一ページ](https://github.com/reactjs/ja.react.dev/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)に訳語を記載する。

## 経緯

結論から言うと、「見出し"Usage"に対する訳語のtypo修正を行おうとして、使用する訳語の判断に私が迷ったため」です。
時系列で言いますと、

1. APIリファレンスの[useIdページ](https://ja.react.dev/reference/react/useId)内の見出しにある、「使用方」がtypoだと判断。
   https://github.com/reactjs/ja.react.dev/blob/fbd04ed0d0fada34b0f5befe83a6589a503c58a5/src/content/reference/react/useId.md?plain=1#L51
2. 他のページでの訳語を確認したところ、合計4パターンあることが判明
   - [使用法](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev+%E4%BD%BF%E7%94%A8%E6%B3%95&type=code)
   - [使い方](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev+%E4%BD%BF%E3%81%84%E6%96%B9&type=code)
   - [使用方](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev+%E4%BD%BF%E7%94%A8%E6%96%B9&type=code)
   - [使用方法](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev+%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95&type=code)
3. 上記の各リンク先にあるコード検索結果で、「使用法」が一番使われていることを確認
4. 続けて[Wikiの訳語の統一ページ](https://github.com/reactjs/ja.react.dev/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)を確認したが、見出し"Usage"に対する訳語の記載が存在していなかった

## 期待される内容

見出し"Usage"に対する、統一された訳語が確定する。

**Comment by smikitky** [comment]
ご指摘ありがとうございます。「使用法」で統一したいと思います。
