### ISSUE TITLE
表記揺れ: アップデート関数 → 更新用関数

### ISSUE THREAD

**Issue by kajirikajiri** [reactjs/ja.react.dev#762]
### Summary

周辺の文脈を見ると、ここは「更新用関数」が適切かもしれません!
「アップデート関数」が１つだけ存在しています。

https://github.com/reactjs/ja.react.dev/blob/0e2e896660d4f71bfdded1535cf0fe853212e4e7/src/content/learn/queueing-a-series-of-state-updates.md?plain=1#L249

ドキュメントの管理をありがとうございます！
openなissueやcloseなissueを確認しましたが、同様のものがなかったのでissueを作成しました！
Typoというよりも表記揺れと感じましたが、このissueを作成させていただきました。
また、アップデート関数という文言は他には存在しないようです。

### Page

https://ja.react.dev/learn/queueing-a-series-of-state-updates

### Details

周辺の文脈を見ると、「更新用関数」という表記が使われており、1箇所だけ「アップデート関数」という表記が使われると、別の関数があるのではないか？という気がしてしまう。

画像

<img width="902" alt="image" src="https://github.com/reactjs/ja.react.dev/assets/37785038/1c6bdd72-494c-4e7d-9324-4a032def386c">

日本語の文字

- 更新用関数（例：n => n + 1）の場合、それがキューに追加されます。
- それ以外の値（例：数値 5）の場合、ここまでのキューの内容を無視する “5 に置き換えよ” のような命令を追加します。

イベントハンドラが完了した後、React は再レンダーをトリガします。再レンダー中に React はキューを処理します。アップデート関数はレンダー中に実行されるため、更新用関数は[純関数](https://ja.react.dev/learn/keeping-components-pure)である必要があり、結果だけを返すようにする必要があります。その中で state をセットしたり、他の副作用を実行したりしないでください。Strict Mode では、React は各更新用関数を 2 回実行します（ただし 2 つ目の結果は破棄されます）が、これによって間違いを見つけやすくなります。

英語の文字

- An updater function (e.g. n => n + 1) gets added to the queue.
- Any other value (e.g. number 5) adds “replace with 5” to the queue, ignoring what’s already queued.

After the event handler completes, React will trigger a re-render. During the re-render, React will process the queue. Updater functions run during rendering, so updater functions must be [pure](https://react.dev/learn/keeping-components-pure) and only return the result. Don’t try to set state from inside of them or run other side effects. In Strict Mode, React will run each updater function twice (but discard the second result) to help you find mistakes.

**Comment by smikitky** [comment]
ありがとうございました！
