### ISSUE TITLE
[Bug]: Images cannot be loaded from `https://placekitten.com` and are not functioning properly as samples.

### ISSUE THREAD

**Issue by hirotomoyamada** [reactjs/ja.react.dev#777]
### Summary

Images cannot be loaded from `https://placekitten.com` and are not functioning properly as samples.

### Page

https://ja.react.dev/learn/manipulating-the-dom-with-refs#example-scrolling-to-an-element

**Comment by smikitky** [comment]
Issues that are common across languages are not fixed at this repository's level. When your PR on the upstream repo (https://github.com/reactjs/react.dev/pull/6963) is merged, it will eventually be included in this repo, too.
