### ISSUE TITLE
[Typo]: チャレンジ問題3の解答のタイプミス

### ISSUE THREAD

**Issue by clumsy-ug** [reactjs/ja.react.dev#800]
### Summary

「UIの記述」内の「コンポーネントを純粋に保つ」にあるチャレンジ問題3つ目の解答の箇所です。

> 発生していることがわかるでしょ。

「発生していることがわかるでしょう。」が正しいかと思います。

該当行
https://github.com/reactjs/ja.react.dev/blob/main/src/content/learn/keeping-components-pure.md?plain=1#L678

### Page

https://ja.react.dev/learn/keeping-components-pure

**Comment by smikitky** [comment]
修正しました、ありがとうございました！
